version: 2
jobs:
  build:
    steps:
      - setup_remote_docker:
          version: 17.09.0-ce
      - checkout
      - run:
          command: docker build -t imkulikov/tidb .
      - run:
          command: docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
      - run:
          command: docker push imkulikov/tidb
workflows:
  version: 2
  build:
    jobs:
      - build
